FROM node:lts-alpine
# installe un simple serveur http pour servir un contenu statique
# RUN npm install -g http-server
# définit le dossier 'app' comme dossier de travail
WORKDIR /app
# copie 'package.json' et 'package-lock.json' (si disponible)
COPY package.json .
COPY package-lock.json .
# installe les dépendances du projet
RUN npm install
#
# copie les fichiers et dossiers du projet dans le dossier de travail (par exemple : le dossier 'app')
COPY --chown=node:node . .

USER node
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
# construit l'app pour la production en la minifiant
# RUN npm run build
EXPOSE 8080
CMD npm run serve