version: '3.7'
services:
  web-app:
    user: "node"
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: "npm run serve"
    environment:
      - NODE_ENV=development
      - container_name: andremeira-front
    volumes:
       - .:/app